---
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'bundle/**/*'
    - '*.gemspec'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'test/**/*.rb'
    - 'spec/**/*_spec.rb'
