---
require:
  - rubocop-rspec
AllCops:
  Exclude:
    - 'bin/**/*'
    - 'bundle/**/*'
    - 'vendor/**/*'
    - '*.gemspec'
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*_spec.rb'
