#!/usr/bin/env ruby
# frozen_string_literal: true

require 'getv'
require 'gli'

module Getv
  # cli class
  class Cli
    def self.output(package, latest: false, json: false)
      key = latest ? 'latest_version' : 'versions'
      result = package.send(key)

      if json
        require 'json'
        result = { 'name' => package.name, key => result }.to_json
      end

      puts result
    end
  end
end

# app class
class App # rubocop:disable Metrics/ClassLength
  extend GLI::App

  program_desc 'Get package version numbers from the web in various ways'

  version Getv::VERSION

  subcommand_option_handling :normal
  arguments :strict

  switch %i[l latest], desc: 'Latest version', negatable: false
  switch %i[j json], desc: 'Output in json', negatable: false
  flag %i[p proxy], desc: 'Web proxy', default_value: nil

  desc 'Get package versions from a Docker or OCI container image registry'
  arg_name 'package_name'
  command :docker do |c| # rubocop:disable Metrics/BlockLength
    defaults = (Getv::Package::Docker.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.flag %i[owner], desc: 'Repository owner',
                      default_value: "'<owner>' if package_name is in format '<registry>/<owner>/<repo>' or '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[repo], desc: 'Repository name',
                     default_value: "'<repo>' if package_name is in format '<registry>/<owner>/<repo>' or <owner>/<repo>, otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[url], desc: 'URL',
                    default_value: "'https://<registry>' if package_name is in format '<registry>/<owner>/<repo>', otherwise #{defaults[:url]}" # rubocop:disable Layout/LineLength
    c.flag %i[user], desc: 'Username', default_value: defaults[:user]
    c.flag %i[password], desc: 'Password', default_value: defaults[:password]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :owner, :repo,
                        :url, :user, :password, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Docker.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from RubyGems.org'
  arg_name 'package_name'
  command :gem do |c|
    defaults = (Getv::Package::Gem.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Gem.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from text file URL'
  arg_name 'package_name'
  command :text do |c|
    defaults = (Getv::Package::Text.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.flag %i[url], desc: 'URL', default_value: defaults[:url]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :url, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Text.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from GitHub commits'
  arg_name 'package_name'
  command :github_commit do |c|
    defaults = (Getv::Package::GitHub::Commit.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.flag %i[owner], desc: 'Repository owner',
                      default_value: "'<owner>' if package_name is in format '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[repo], desc: 'Repository name',
                     default_value: "'<repo>' if package_name is in format '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[branch], desc: 'Repository branch', default_value: defaults[:branch]
    c.flag %i[token], desc: 'Token', default_value: defaults[:token]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :owner, :repo, :branch, :token, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      package = Getv::Package::GitHub::Commit.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from GitHub releases'
  arg_name 'package_name'
  command :github_release do |c|
    defaults = (Getv::Package::GitHub::Release.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.flag %i[owner], desc: 'Repository owner',
                      default_value: "'<owner>' if package_name is in format '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[repo], desc: 'Repository name',
                     default_value: "'<repo>' if package_name is in format '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[token], desc: 'Token', default_value: defaults[:token]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :owner, :repo,
                        :token, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::GitHub::Release.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from GitHub tags'
  arg_name 'package_name'
  command :github_tag do |c|
    defaults = (Getv::Package::GitHub::Tag.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.flag %i[owner], desc: 'Repository owner',
                      default_value: "'<owner>' if package_name is in format '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[repo], desc: 'Repository name',
                     default_value: "'<repo>' if package_name is in format '<owner>/<repo>', otherwise just package_name" # rubocop:disable Layout/LineLength
    c.flag %i[token], desc: 'Token', default_value: defaults[:token]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :owner, :repo,
                        :token, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::GitHub::Tag.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from a Helm chart repository'
  arg_name 'package_name'
  command :helm do |c|
    defaults = (Getv::Package::Helm.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.flag %i[chart], desc: 'Chart name', default_value: 'package_name'
    c.flag %i[url], desc: 'URL', default_value: defaults[:url]
    c.flag %i[user], desc: 'Username', default_value: defaults[:user]
    c.flag %i[password], desc: 'Password', default_value: defaults[:password]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :chart, :url,
                        :user, :password, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Helm.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from XML file URL'
  arg_name 'package_name'
  command :xml do |c|
    defaults = (Getv::Package::Xml.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.flag %i[url], desc: 'URL', default_value: defaults[:url]
    c.flag %i[xpath], desc: 'XPath', default_value: defaults[:xpath]
    c.switch %i[link_value], desc: 'Use the value (target) of links rather than the content (display text)',
                             negatable: false, default_value: false
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :url, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:link] == 'value' if options[:link_value]
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Xml.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from npm at registry.npmjs.org'
  arg_name 'package_name'
  command :npm do |c|
    defaults = (Getv::Package::Npm.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Npm.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  desc 'Get package versions from the Python Package Index at pypi.org'
  arg_name 'package_name'
  command :pypi do |c|
    defaults = (Getv::Package::Pypi.new 'name').opts
    c.flag %i[select_search], desc: 'Regex version selection search', default_value: defaults[:select_search]
    c.flag %i[select_replace], desc: 'Regex version selection replace', default_value: defaults[:select_replace]
    c.flag %i[reject], desc: 'Regex version rejection', default_value: defaults[:reject]
    c.switch %i[invalid_versions], desc: 'Include invalid semantic versions', negatable: false, default_value: false
    c.flag %i[semantic_select], desc: 'Semantic version selection (comma delimited)',
                                default_value: defaults[:semantic_select]
    c.action do |global_options, options, args|
      help_now! unless args.size == 1

      opts = global_options.merge(options)
      opts = opts.slice :select_search, :select_replace, :reject, :semantic_only, :semantic_select, :proxy
      opts = opts.delete_if { |k, v| v.nil? || v == c.flags[k].default_value }
      opts[:semantic_only] = !options[:invalid_versions]
      opts[:semantic_select] = opts[:semantic_select].split(',') unless opts.fetch(:semantic_select, nil).nil?
      package = Getv::Package::Pypi.new args[0], opts
      Getv::Cli.output(package, latest: global_options[:latest], json: global_options[:json])
    end
  end

  pre do |_global, _command, _options, _args|
    # Pre logic here
    # Return true to proceed; false to abort and not call the
    # chosen command
    # Use skips_pre before a command to skip this block
    # on that command only
    true
  end

  post do |global, command, options, args|
    # Post logic here
    # Use skips_post before a command to skip this
    # block on that command only
  end

  on_error do |_exception|
    # Error logic here
    # return false to skip default error handling
    true
  end
end

exit App.run(ARGV)
